[package]
name = "openairac-store"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
openairac-model = { path = "../openairac-model" }
openairac-magnetic = { path = "../openairac-magnetic" }
rusqlite.workspace = true
chrono.workspace = true
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
anyhow.workspace = true
thiserror.workspace = true
tracing.workspace = true
