[package]
name = "openairac-export-xplane"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
openairac-model = { path = "../openairac-model" }
openairac-store = { path = "../openairac-store" }
anyhow.workspace = true
chrono.workspace = true
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
tracing.workspace = true
