[package]
name = "openairac-export-lnm"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
openairac-model = { path = "../openairac-model" }
openairac-store = { path = "../openairac-store" }
openairac-export = { path = "../openairac-export" }
openairac-export-xplane = { path = "../openairac-export-xplane" }
anyhow.workspace = true
chrono.workspace = true
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
rusqlite.workspace = true

[dev-dependencies]
openairac-ingest = { path = "../openairac-ingest" }
